[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli

build_flags =
  -D DISABLE_SOFTWARE_RESET
  -D USB_DISABLED
  -D USB_CUSTOM

platform_packages =
  framework-arduinoteensy @ symlink://packages/framework-arduinoteensy
